# Generated by Django 6.0.5 on 2026-05-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_category_course_instructorprofile_module_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='about',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='expertise',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='insructor_picture',
            field=models.ImageField(default='Instructor_profile_logo.png', upload_to='instructor_picture'),
        ),
    ]
