# Generated by Django 6.0.5 on 2026-05-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_alter_instructorprofile_about_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order_number']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order_number']},
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
