# Generated by Django 6.0.5 on 2026-06-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_alter_lesson_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Instructor', 'Instructor')], default='Student', max_length=50),
        ),
    ]
