# Generated by Django 6.0.5 on 2026-06-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='insructor_picture',
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='instructor_picture',
            field=models.ImageField(default='Instructor.png', upload_to='Instructor_Pictures'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='order_number',
            field=models.PositiveIntegerField(),
        ),
    ]
