# Generated by Django 6.0.5 on 2026-06-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_remove_instructorprofile_insructor_picture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
    ]
