# Generated by Django 6.0.5 on 2026-06-04 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_alter_user_role'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_course_items', to='instructor.course')),
                ('student_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_user_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
