# Generated by Django 6.0.5 on 2026-06-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_remove_instructorprofile_insructor_picture_and_more'),
        ('student', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='course_object',
            field=models.ManyToManyField(related_name='enrolled_course', to='instructor.course'),
        ),
    ]
